### ISSUE TITLE
Invalid parameter(s): license_key

### ISSUE THREAD

**Issue by Externocleidomastoideo** [Joel2B/WP-Script-API#4]
Hey! Themes are working and key is valid, but when trying to use any plugin, as wps mass embedder im getting a problem that says: 
All videos may have been already imported for the current search
Then if I go to logs, you can see Error Invalid parameter(s): license_key
No matter what plugin, even WP Script core gets that problem, is there anything wrong??
Anyways, thanks for everything!!!

**Comment by Joel2B** [comment]
hi, i just tested the wp-script plugin (2.1.9) and its plugins such as wps mass embedder and they seem to work fine in the latest version of wordpress, what version of wp-script do you have?

**Comment by Externocleidomastoideo** [comment]
Im working with WordPress6.1.1

**Comment by Externocleidomastoideo** [comment]
Im working with wordpress 6.1.1 and WP-Script core 2.2.7

**Comment by Externocleidomastoideo** [comment]
Okay, just reinstalled the WP-Script,  to downgrade to 2.1.9 to test and now everything works... The problems comes when you update to 2.2.7, so as long as you stay at 2.1.9 everything is okay
Thanks!!!

**Comment by Joel2B** [comment]
well, create a new issue when any plugin except wp-script stops working or fails in something, 
to update the whole api to the latest version.
