### ISSUE TITLE
Not working themes and plugins

### ISSUE THREAD

**Issue by michaelroevievictoria** [Joel2B/WP-Script-API#5]
I try to use all the modified themes and  plugins using this link https://appsdev.cyou/wp-script-api/

Im trying to use the mass embedder 
but seems its not working 

![image](https://user-images.githubusercontent.com/6307916/222083918-3e187f6d-f56c-4af7-9714-ada9fa30252e.png)
I try to check the url api

but still white screen 
![image](https://user-images.githubusercontent.com/6307916/222084029-d68c5e26-0eae-439c-889b-53402666fdc4.png)

I already try the read me file 
![image](https://user-images.githubusercontent.com/6307916/222084164-f7730ed0-23d9-436a-a065-720f838f874d.png)

but seems its not there 
![image](https://user-images.githubusercontent.com/6307916/222084415-2d32867e-ac77-43ab-a785-513d2c41d0ac.png)
![image](https://user-images.githubusercontent.com/6307916/222084550-818ed273-85f2-4226-a9c6-3d30b38cd10c.png)

**Comment by roevieDev** [comment]
you need wp-core and then edit, all the contents are now free

closing this.

**Comment by michaelroevievictoria** [comment]
you need wp-core and then edit, all the contents are now free

closing this.
